spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flyer?autoReconnect=true&failOverReadOnly=false&maxReconnects=10&userSSL=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:

key:
  uploadDir: C:\Users\User\IdeaProjects\flyerGraphic\upload
